modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="ftbconv"
version="${file.jarVersion}"
displayName="FTB quest lang converter"
description=''' Stuff '''

[[dependencies.ftbconv]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ftbconv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"